### ISSUE TITLE
Window Height Bug

### ISSUE THREAD

**Issue by dentalala** [danielbuechele/goofy#222]
Every time the app starts it becomes taller than before. Window height increases with every launch.

**Comment by viaphp** [comment]
I'm also having this problem. Every time I restart Goofy (quitting app and launching again or by OS X system restart) it increases height two or three times (it appears to be a random problem) and then goes back to height "defined" by user.

**Comment by eklundchristopher** [comment]
I'm experiencing this issue as well. It appears as though the added height is equal to that of the default OSX application toolbar.

![application-toolbar](https://cloud.githubusercontent.com/assets/933531/13810295/66c2fff8-eb6f-11e5-9638-58c5006ee7d1.png)

I measured this by having Slack positioned below Goofy and aligned Goofy with the top of Slack's toolbar. Upon restart, Goofy would end at the bottom of the Slack toolbar rather than the top, as it was previously set to.

As both of the previous people mentioned, this only occurs during launch. Here's visual representation.

![goofy-height-issue](https://cloud.githubusercontent.com/assets/933531/13810511/841f4916-eb70-11e5-9b94-45dbcee9bd94.gif)

**Comment by danielbuechele** [comment]
Thanks @eklundchristopher this is a good hint! However I still don't know a solution for this, but at least I know in which direction to look for it.

**Comment by dentalala** [comment]
It doesn't reproduce anymore in macOS Sierra. Goofy window height stays constant.
