### ISSUE TITLE
Multi-services messanger app

### ISSUE THREAD

**Issue by iBobik** [danielbuechele/goofy#293]
How about to create app supporting also other services what have web app (Slack, Mattermost, Hangout, ...) and allow to use them simultaneously?

UI could be simple like from Slack app (sidebar will contain multiple account from one or multiple services):

![slack-sidebar](https://cloud.githubusercontent.com/assets/614232/19894342/f334c768-a04c-11e6-9097-77fe4e830312.PNG)

It will probably be good to design plugin architecture, so adding new service driver will require to write only some JavaScript integrating specific web app, not common thinks like handling system notifications and common UI.

It also could be easily portable to other platforms, because service drivers will be multi-platform.

What do you thing about it?

**Comment by danielbuechele** [comment]
Franz (http://meetfranz.com/) does exactly that. I am not a fan of throwing
these things together.

On Nov 1, 2016, at 4:12 PM, Jan Pobořil <notifications@github.com> wrote:

How about to create app with other services what have web app (Slack,
Mattermost, Hangout, ...) and allow to use them simultaneously?

UI could be simple like from Slack app (sidebar will contain multiple
account from one or multiple services):

[image: slack-sidebar]
<https://cloud.githubusercontent.com/assets/614232/19894342/f334c768-a04c-11e6-9097-77fe4e830312.PNG>

It will probably be good to design plugin architecture, so adding new
service driver will require to write only some JavaScript integrating
specific web app, not common thinks like handling system notifications and
common UI.

It also could be easily portable to other platforms, because service
drivers will be multi-platform.

What do you thing about it?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/danielbuechele/goofy/issues/293>, or mute the thread

**Comment by iBobik** [comment]
Yes, Franz does the same but it do not seems to be open source.



Jan Pobořil

2016-11-01 23:58 GMT+01:00 Daniel Büchele <notifications@github.com>:

> Franz (http://meetfranz.com/) does exactly that. I am not a fan of
> throwing
> these things together.
>
