### ISSUE TITLE
Set focus to input bar when app is focused (v3.0.0 Beta)

### ISSUE THREAD

**Issue by duk242** [danielbuechele/goofy#322]
When you swap from any other app to Goofy, the input bar isn't focused, so you have to click on the input bar to type a message.

From the looks of it, it's focusing on the left hand side of the window where all the contacts are.

**Comment by SPGWhistler** [comment]
I looked into this, and it seems like facebook's code is having an issue with electron - because even when I trigger a click on the various elements manually, it still will not focus. In fact, it will only focus if you actually click with the mouse.

I added this to renderer.js:
```
app.on('browser-window-focus', () => {
	setTimeout(() => {
	    	webview.executeJavaScript("document.querySelector('._1ht5._2il3._5l-3').click();", true);
	}, 550);
});
```
(note: in my case, that selector actually worked - I'm sure it will change based on the specific build of their css, so you may need to update it if trying for your self.)

**Comment by danielbuechele** [comment]
Luckily the hashed CSS-classnames are stable. Goofy relies heavily on it, so this is fine.
Perhaps the `click`-event needs to be triggered on another element? Or we could try to trigger a `focus`-event.

**Comment by SPGWhistler** [comment]
I tried a few different elements with both click and focus and neither seemed to work. Plus there is only one error in the console and it doesn't seem related at all. I'll keep messing with it though.

**Comment by ragunaru** [comment]
Any news on this? The lack of autofocus is a major usability issue, for me personally anyway.

**Comment by SPGWhistler** [comment]
I've tried several approaches and can not get it to work. If anyone has any ideas, I'm happy to try them.

**Comment by Etheryte** [comment]
I've created [a pull request](https://github.com/danielbuechele/goofy-core/pull/1) that should should resolve this issue.

**Comment by pyrmont** [comment]
Hope this pull request can get merged in soon!
