### ISSUE TITLE
Facebook Phone Number Bar Appearing at Top of Application

### ISSUE THREAD

**Issue by MustafaHaddara** [danielbuechele/goofy#331]
Facebook is asking for my phone number. I don't want to give Facebook my phone number. 

I also can't click the 'X' on Facebook's popup because of Goofy's menu buttons. 

<img width="1000" alt="screen shot 2017-03-02 at 10 59 01 am" src="https://cloud.githubusercontent.com/assets/11722214/23515300/c3b9b47c-ff37-11e6-9d42-006195624cee.png">

**Comment by danielbuechele** [comment]
Ok, we can hide this bar. However, we need the CSS-class of it. As Facebook already has my phone number, can you try to look up the CSS-class of this bar?

**Comment by MustafaHaddara** [comment]
I managed to re-position the 'X' on the Facebook popup by resizing the window, and was able to close the popup that way, so I can't get the CSS-class of the bar. 

If I do see it again, I'll grab the class and update this issue.

**Comment by jklp** [comment]
Might no longer be there since the switch to messenger.com in v3.4.0.  

Created a new account and couldn't get to appear, also removed phone number from my existing account and also couldn't get to appear.  

Please re-open if still occurring and if possible - paste the CSS selector into the ticket?  

Thanks!
