### ISSUE TITLE
Missing touchbar actions

### ISSUE THREAD

**Issue by cratrifork** [danielbuechele/goofy#335]
In version 2, I seem to remember that there was a Touchbar item to choose smileys.

It would be a nice addition to add some functionality to the Touchbar.

**Comment by danielbuechele** [comment]
This is blocked until electron supports the TouchBar.
Here is their issue: https://github.com/electron/electron/issues/7781

**Comment by janclarin** [comment]
@danielbuechele, slightly off-topic, but what was the main reason for switching to Electron? There are other electron apps that wrap Messenger already like https://github.com/sindresorhus/caprine.

Not switching to Electron, would've given more flexibility with macOS like resolving this issue.

**Comment by danielbuechele** [comment]
Electron just added Touch Bar support: https://electron.atom.io/blog/2017/03/08/touch-bar-support

**Comment by LanderN** [comment]
@danielbuechele I checked out the latest master version. I completely understand it is a WIP version, but an emoji button would be a lot more helpful than buttons to switch conversations. Keep up the good work!
(I can only dream: thumbs up button? GIFs? Stickers?)

**Comment by danielbuechele** [comment]
With version 3.1.0 there is basic TouchBar support. But I fully agree that we should continue discussion on what the TouchBar support should look like. I want to give the current implementation a chance to try out, but I agree that at least the like-button should be available on the TouchBar.

**Comment by LanderN** [comment]
I would argue that an emoji button is at least as important, seeing it was there in the non-electron version and all native MacOS messaging apps. I see that the Electron TouchBar API does not (yet) provide an emoji button. A custom implementation would probably be overkill, although it would be very cool if it would display the facebook emoji instead of the Apple ones. 😎

**Comment by Vilscon** [comment]
I think it's interesting to note is that, as far as I can tell, the Touchbar integration (emojis) with version 2 is a native thing (text-input field) and not done custom by Daniel. That emojis are now missing from the touchbar in version 3 is simply unintended result of moving to Electron. 

But Electron meanwhile introduced Touchbar support, so sooner than later we'll see it integrated into Goofy as well. 

_Currently running V2 and V3 side by side to test performance and energy usage._

**Comment by jklp** [comment]
Changed the way the touchbar works now - instead of using to swap between conversations, can now perform actions on the conversation e.g. mute, archive, like previous conversation, etc.  

Was thinking about putting stickers / gifs etc but lets see how we do with these first (and we can look at adding more later).  

This was completed in v3.3.6
