### ISSUE TITLE
Quits when opening external links

### ISSUE THREAD

**Issue by sean-smith** [danielbuechele/goofy#341]
Recently Goofy started crashing when opening links. Is anyone else experiencing this problem?

**Comment by danielbuechele** [comment]
Which version of Goofy are you using?

On Mar 12, 2017, at 7:20 PM, Sean Smith <notifications@github.com> wrote:

Recently Goofy started crashing when opening links. Is anyone else
experiencing this problem?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/danielbuechele/goofy/issues/341>, or mute the thread

**Comment by sean-smith** [comment]
3.0.3

**Comment by sean-smith** [comment]
works now. Not sure what I did besides restarting it.
