### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by mrleblanc101** [danielbuechele/goofy#345]
Hi,
Providing a changeling would be very nice for your user.
Either through the README.md like most repo, through the app or through a blog entry on the Good Website would be very nice as we don't know what changed unless we check the issues and pull request here.

**Comment by Etheryte** [comment]
In my opinion, [the release feed](https://github.com/danielbuechele/goofy/releases) along with [`git log`](https://git-scm.com/docs/git-log) covers the changes in sufficient detail.  

Working on a project is always a limited set of time. I would much rather have the main developer work on bug fixes instead of editing a change log when the information is already available in some form.
