### ISSUE TITLE
Notifications When I Send a Message

### ISSUE THREAD

**Issue by aleminopuy** [danielbuechele/goofy#369]
I get a notification in notification center whenever I send a message. It contains text from the message I just sent. It looks just like a notification when I get a message, but it's my own words right after I hit send. Is this supposed to happen? It seems kinda weird. (And sorry if this issue has already been reported, my search of other issues was pretty quick.)

<img width="500" alt="notifications" src="https://cloud.githubusercontent.com/assets/18608490/25147505/5dfacc54-243d-11e7-94d6-e7c44a5cfcb8.png">

**Comment by martinwolf** [comment]
Same problem here.

**Comment by ryan4888** [comment]
+1

**Comment by broketheinterweb** [comment]
Facebook messenger itself has been doing this to me. It may be on their side.

**Comment by drobati** [comment]
Version 3.2.2 (2001)

**Comment by Ghilteras** [comment]
Looks like the bug is still present in version 3.2.2

I systematically get notifications for messages I send

**Comment by doomchild** [comment]
I'm seeing this behavior in 3.2.2 as well.

**Comment by unremarkablegarden** [comment]
Me too

**Comment by jrozelle** [comment]
Same here

**Comment by MikaelStrom** [comment]
Same here

**Comment by warudin** [comment]
Same here (v. 3.2.2)

**Comment by foreverburgo** [comment]
Also getting this on 3.2.2

**Comment by jamesaspence** [comment]
I am as well. It comes and goes but is pretty consistent. Maybe one of us smart folks should do something about it :p

**Comment by petr-ujezdsky** [comment]
Adding more comments like `same here` etc. won't fix this issue. Posting this comment you only notify subscribed people about, well, nothing.

I am waiting for resolution or relevant information and the only thing I get via notifications are those comments :( And I do not want to unsubscribe because I want to be notified on resolution :)

**Comment by Wemps** [comment]
Adding a $10 bounty for this bug. Fix it and I will Venmo you money. I cannot stand this.

**Comment by gartz** [comment]
Hey @Wemps fell free to send that sweet bug bounty to my Venmo: https://venmo.com/gartz

btw, the bug was annoying me too, hope they merge and release it soon if not, you can clone the project and run locally in that meanwhile.

**Comment by gartz** [comment]
A quick tutorial how to use the fork with the patch:

```bash
git clone --recursive https://github.com/danielbuechele/goofy.git
cd goofy
git submodule update --init --recursive
cd app
git remote add gartz https://github.com/gartz/goofy-core.git
git fetch gartz && git checkout gartz master
cd ..
NODE_ENV=production npm run build-mac
```
You can replace the `build-mac` by `build-win` if you're in a windows machine.

After that you will have your binary file inside the `dist` folder. It will show an signature failure alert when you start, because you build it without using the author app signature, but that is fine. The app will run fine with the bug fixed.

My `master` branch also includes a performance issue fix.

Then let's hope that @danielbuechele like the patch and have time to release the patch to everybody :)

**Comment by danielbuechele** [comment]
this should be fixed in version 3.3.0 that was just released

**Comment by unremarkablegarden** [comment]
Not fixed. Still the same issue.

**Comment by ryndshn** [comment]
i also experienced this issue last night, after updating

**Comment by danielbuechele** [comment]
What language are you using messenger in?
To detect if it's a message sent from you, I am checking if the preview text in the sidebar is prefixed with "You:"

**Comment by unremarkablegarden** [comment]
@danielbuechele English. OS X 10.12.6

**Comment by ryndshn** [comment]
i’m using it in english. i believe it occurred when sharing a facebook post in a private message (from facebook).

**Comment by danielbuechele** [comment]
Ok, can you confirm this is happening for every message you send? As I said, I am checking for the exact string in the message preview in the sidebar. If it starts with "You:" the notification should not be sent. But for example if it starts with "You sent a photo" (missing the colon) the notification is still sent.
Can you confirm this happens just for plain messages as well?

**Comment by ryndshn** [comment]
It occurs with "You sent a link."

**Comment by danielbuechele** [comment]
Ok, does anyone have an idea how we can fix this? I mean, we can look for lines starting with "You", but when someone writes you a message "You are awesome" you won't get a notification.

**Comment by broketheinterweb** [comment]
It really depends on how Facebook messenger itself delineates between who sent the message. If a simple property like "profile_id" could be obtained from any of these elements, this would be such an easy fix. But the way the previous dev wrote the check was by using a now-useless translation tag-- never a good idea because of how often Facebook changes these things. We can try to think of good-enough fixes, but they will change too and we'll be right back here.

The only good-programming fix is the one facebook uses itself-- especially because we're not even using their API anymore. I spent a good few hours trying to fix this myself, and while the place where it's broken is obvious, a replacement for that if statement is not so obvious.

**Comment by gartz** [comment]
The fix works, sadly the merge for version 3.3.0 reverted my patch.

**Comment by danielbuechele** [comment]
Sorry for messing up the merge, could you send another PR?

**Comment by gartz** [comment]
I will, was very busy lately and could not fix it. I will send in a few minutes

**Comment by gartz** [comment]
Hope this helps again, there it is the patch again, it works in any language. :)

**Comment by Wemps** [comment]
@gartz as soon as I get the update you got the money (will either build it myself when I get back this weekend or wait for next release)! Thanks for taking the time to address this!

**Comment by danielbuechele** [comment]
I'll create an update 3.3.1 right now so @gartz get's his well deserved money! Thanks for helping!

**Comment by gartz** [comment]
@Wemps and @danielbuechele you guys are awesome, remind me why I choose to programme as my career. I'm very happy to contribute here, and thankful for @danielbuechele project.

**Comment by Wemps** [comment]
💸
