### ISSUE TITLE
link in convo doesn't open in safari but in the webview

### ISSUE THREAD

**Issue by krishnamannem** [danielbuechele/goofy#37]

**Comment by lukasschwab** [comment]
Running into the same issue––if I click a link, it tries to open in the webview instead of in my browser window. I am given a screen as if the app is loading (see image), but it never does.
![screen shot 2015-04-09 at 5 30 17 pm](https://cloud.githubusercontent.com/assets/4955943/7079833/29f79320-dede-11e4-9a24-5f022be54958.png)
