### ISSUE TITLE
Links don't open when clicked on

### ISSUE THREAD

**Issue by ssssamstrup** [danielbuechele/goofy#378]
Current behavior: When people send you a link,  nothing happens upon clicking the link.
Expected behaviour: When clicking a link, it should open in your browser and switch to the browser.

Macbook Pro (Retina, 15-inch, Mid 2015)
MacOS: 10.12.4 (16E195)
Goofy: Version 3.2.0 (2001)

**Comment by AZ42** [comment]
Same problem. Same computer. Using Chrome as defult.

**Comment by Anahkiasen** [comment]
Same issue here, same versions

**Comment by RvMouche** [comment]
Yea me too, dragging them to chrome/safari works. No clue why yet.

**Comment by bboyairwreck** [comment]
It's been awhile since i've dont webdev and im not familiar with electron. But I believe the issue relies somewhere in in the assets/fb.js [setInterval()](https://github.com/danielbuechele/goofy-core/blob/8090245b2fb97876ec3b4f93dd1b3058b99869e4/src/assets/fb.js#L87) method that handles external links?

**Comment by sumanvyj** [comment]
setInterval does seem unreliable; attached a PR that uses https://electron.atom.io/docs/api/webview-tag/#event-new-window

**Comment by jklp** [comment]
Am closing for now as can't seem to replicate on v3.3.3.  If this is still happening please reopen and we can investigate further.
