### ISSUE TITLE
Button to hide sidebar

### ISSUE THREAD

**Issue by d4rky-pl** [danielbuechele/goofy#4]
Most of the time when I'm talking with someone, I don't really need the list of all my friends hanging around and taking unnecessary space. It'd be great if there was a small, slick button somewhere that'd show and hide sidebar when necessary.

I'd implement it myself and send a pull request but I need #3 to do so :)

**Comment by danielbuechele** [comment]
Could be a nice addition! I am not sure if you know this, but if you make the window smaller, the left list collapses into a smaller version. So I should be as easy as making this not only triggered by a media-query, but also a class we toggle on the body-element.
The most important question for me is, where to put the toggle. I am not a big fan of putting this feature in the main interface, perhaps we can find a place for it in the menu?

**Comment by d4rky-pl** [comment]
Yeah, the position of button is something I didn't think through. Hiding it in menu may not be a great idea but if you're against augmenting UI then it's probably the only way to go.

**Comment by TCB13** [comment]
I thing the bar should not be hidden. There should be an option to open a conversation on a new window (right click on person) (without the bar) and then the use can close que main window containing the sidebar...

**Comment by JadenGeller** [comment]
@TCB13 +1

**Comment by tonton974** [comment]
@danielbuechele Problem is (just for me?) I get this when I reduce my window width:
![goofy](https://cloud.githubusercontent.com/assets/3071585/8263088/0fc1f0ae-16d8-11e5-92f9-7da90375f404.png) *note: No unread messages when picture taken.*

Having a button is a nice idea but i'd rather have one **showing** the sidebar since it is the less interesting stuff.
And then maybe, a pin on there to...pint it the way it is displaying now.

I would suggest to just mimic the messenger smartphone-app behavior in that way.
