### ISSUE TITLE
Endless update loop

### ISSUE THREAD

**Issue by simplenotezy** [danielbuechele/goofy#404]
![image](https://user-images.githubusercontent.com/3786627/36535590-e7c73d9e-17d2-11e8-86dd-f956c641ae2b.png)

Clicking "update and restart" brings the same update up next time

**Comment by PEZ** [comment]
Continuing the discussion from #432 here instead. I can reproduce this by using starting version 3.3.4. It is slightly different though. What happens for me is that I click the ”Install and Restart” button and then Goofy closes and nothing more happens (that I can see). If I start the app again the dialog pops up and the same things happen again.

Since I can repro this, maybe I can help diagnose it some? I can build the app myself and goof around (couldn't resist the pun!) some if that is what it takes. Are there some logs I should keep an eye on?

**Comment by PEZ** [comment]
I tried to build it now and run into issues. They can probably be fixed, but I am also willing to just try diagnose this using the built app. Let me know how I can help.

**Comment by PEZ** [comment]
Yeah, I noticed it was a pretty old Electron in play. I'll see if I can get the project to build on my home computer and if I can figure out about `did-get-redirect-request` and the new updated. Will get back here if I get stuck. Would feel pretty nice to have contributed a PR to this project. I am a heavy Goofy user.

**Comment by PEZ** [comment]
As I don't have experience with building Electron apps I'll concentrate on seeing if I can fix the update issue w/o bumping up to v3.

I can build the app if I bump Electron to version `2.0.14`. But my build seems unable to cache anything and I have to login every time I restart the app. (Not sure if this is to be expected).

More important: Building a Goofy dist, backing the version to `3.3.4` and starting that, the auto-update is not triggered at all, so not sure how to proceed right now.

**Comment by jklp** [comment]
Hey sorry been finding it hard to find time to work on Goofy in the lead up to xmas.  Yeah sometimes you need to clear the cache (try deleting `/Library/Application Support/goofy-builder` and `goofy-core`).  

With auto-update not working, not sure if Nuts needs to be updated to use 3.x, though I do recall seeing some code which disables auto-updating in dev mode?

**Comment by jklp** [comment]
@PEZ Hey Pez I managed to recently update v3.4.0 to Electron 4.  If it was a problem with Electron 2 and below's update code - it might have to take a couple more versions of Goofy for it to "catch up".

Either way I'll close for now and can be re-opened if we experience again.
