### ISSUE TITLE
Make updating optional?

### ISSUE THREAD

**Issue by PEZ** [danielbuechele/goofy#432]
When Goofy discovers that a new version is available it puts up a modal with an ”update now” button. There is no way to cancel this dialog. This is made worse by the endless loop of updating attempts (#404).

**Comment by brysnik** [comment]
.... or make it work (as apparently it does not) :>

**Comment by jklp** [comment]
Oh damn is the endless loop happening for you? I've been testing that on my end with the last couple of builds and haven't been able to reproduce.  Do you know what version you're coming from?

**Comment by brysnik** [comment]
I have the same issue. macbook pro 2017 15', os is Mojave 10.13.6, goofy version 3.3.1/2/3/4, for now the issue is replicating for every single version I've been running. I'm getting update dialog then after goofy closes nothing happens, and after I start the app again it asks for update again.

**Comment by PEZ** [comment]
@jklp , I have the same situation as @brysnik describes. I should be able to repro at will by installing an older version. Is there something I can do to help pinpoint the issue? Paste the contents of some log or whatnot. Maybe we should continue this in #404

**Comment by jklp** [comment]
@PEZ Sounds good - can leave this issue for discussing to make updating optional

**Comment by jklp** [comment]
As of v3.4.0, have updated Goofy to Electron 4 and using autoUpdater with update.electronjs.org (instead of nuts).  

Unfortunately due to the way the update API works, making updating doesn't seem to be an option (though there is an option to restart now or later - which I've implemented).

Let's see how v3.4.0 goes and if we're still getting update problems more than happy to reopen this.
