### ISSUE TITLE
Styling Appears Broken

### ISSUE THREAD

**Issue by Matthew-Pollock** [danielbuechele/goofy#435]
![screen shot 2019-01-22 at 11 50 51 am](https://user-images.githubusercontent.com/24258758/51551254-16267180-1e3c-11e9-814c-322f2c623d5d.jpg)
As seen here the styling of the messages seem broken. I assuming this has to do with the new Messenger Look and Feel being rolled out slowly

**Comment by jklp** [comment]
I just did a test on my local copy and can't seem to replicate (you're pointing out the speech bubbles specifically?)

There's no styling that should be effecting the speech bubbles that I know - can you refresh the app (cmd-r) or just restart and let me know if it's still happening.  Actually if possible, could you load messenger.com in Chrome on your machine and see if it's happening there too?  Maybe they are rolling out something which is breaking on Chrome / Mac which is affecting you atm?

**Comment by jklp** [comment]
Hi sorry for the delay, I was in an accident last week and only just got well enough to jump back on the computer (though with only use of one arm - for now).

I just had a look at the two screen shots and I can't seem to tell which aspect you're referring to as broken (I asked if it was the speech bubbles but you ignored my question in your response). 

Maybe give v3.4.0 a go - I've since updated to use messenger.com and also updated to v4 of Electron - which might have solved some rendering issues.
