### ISSUE TITLE
It's broke.

### ISSUE THREAD

**Issue by thethiefprince** [danielbuechele/goofy#436]
The entire app has stopped working for me on my MacBook. Specs are below and I am on the latest software version.

MacBook Pro (15-inch, 2017)
3.1 GHz Intel Core i7
16 GB 2133 MHz LPDDR3
Radeon Pro 560 4096 MB
Intel HD Graphics 630 1536 MB

I use this app everyday and LOVE it! Please make it work again!

Thanks,

Trey

**Comment by achtan** [comment]
same here, i see only white window....

**Comment by jklp** [comment]
Hi sorry for the delay, I was in an accident last week and only just got well enough to jump back on the computer (though with only use of one arm - for now).  

Are you still experiencing this - might be related to #435.  

Also recently updated to Electron 4 in v3.4.0 and also is now using messenger.com - which might have fixed things.

If you could please update and let me know - otherwise I'll dig into it more.

**Comment by achtan** [comment]
@jklp yes v3.4.0 is working! thx
