### ISSUE TITLE
Notifications sent for silenced groups and users.

### ISSUE THREAD

**Issue by kosigz** [danielbuechele/goofy#54]
The app should not send push notifications when FB would not.

**Comment by ialexryan** [comment]
This has occurred for me as well but I can't reproduce it.

**Comment by kennysong** [comment]
This seems to be the expected behavior as documented [in the FAQ](http://www.goofyapp.com/faq.html):

"You can mute conversations in the settings, but Goofy will still show you notifications and a dock badge for muted conversations. This is because I can not detect from the HTML of the page if a conversation is muted or not. If anyone has a good idea for this, please let me know."

**Comment by ialexryan** [comment]
That FAQ dates from before the messenger.com update. It might be possible to detect muted conversations now.

**Comment by kennyeni** [comment]
I think it worked a week or two ago (maybe I just don't recall it?), but now it becoming very annoying to still have notifications from muted conversations :S 
As a work-around (not really, but keeps me sane) I removed goofy's permissions on my Mac to show notifications, the badge count should be enough for now...

**Comment by tenpaiyomi** [comment]
@danielbuechele this issue should probably be closed as well, since it was resolved in a different issue/commit.
