### ISSUE TITLE
Run app as menu bar bar app instead of active app

### ISSUE THREAD

**Issue by mgingras** [danielbuechele/goofy#67]
Low priority, but would be cool if it could run as a menu bar app instead of as an active app.

**Comment by mgingras** [comment]
As a hack you can edit the info.plist and add
```xml
  <key>LSUIElement</key>
  <string>1</string>
````

**Comment by danielbuechele** [comment]
I already started working on this, hope to finish it soon: https://github.com/danielbuechele/goofy/blob/master/Goofy/AppDelegate.swift#L109-L116

**Comment by mgingras** [comment]
@danielbuechele Dope, thanks for the quick response. Nice work so far.

**Comment by Sheraff** [comment]
+1 for a menubar module. Even though, for my own purposes, i'd like it better as a reminder that i have unread/new messages: you can see in the image below that i have notifiers for github, facebook, stackexchange, gmail. 
![screen shot 2015-04-26 at 15 15 53](https://cloud.githubusercontent.com/assets/1325721/7337351/35f299d0-ec27-11e4-83e6-6032d29f4ab3.png)
Their main function is to light up (like the red gmail) when there is content to be seen, be black when everything is fine, be grayed out when there is a connection issue. I find these to be good companion notifiers for bigger apps / full blown websites.

**Comment by kennysong** [comment]
Menu bar would be great. I think this could just copy the behavior of [Current](http://currentformac.com/) with the icon highlighting for unread messages.

**Comment by SidneyS** [comment]
I completed integration of this feature, as Current is not really a viable option anymore. It is a basic implementation at:
https://github.com/danielbuechele/goofy/pull/201

**Comment by PrinceBalabis** [comment]
This never worked properly for me, when starting the app you always have to manually toggle the menu bar manually, and when its on, it does notthing when clicked. The Main window never opens, so it's basically featureless for me.

**Comment by laurentNoudohounsi** [comment]
@mgingras I don't think your hack is a good option since it's a kind of hardcoding.
A best way would be to use `NSApp.setActivationPolicy(.Accessory)` because it changes the LSUIElement programatically.

@danielbuechele I tried to add this feature. First thing was to change https://github.com/danielbuechele/goofy/blob/master/Goofy/AppDelegate.swift#L327 ( `button.action = Selector("statusItemClicked:")` ) with:
`button.action = #selector(self.statusBarItemClicked)`

When I will have more free time I will investigate but before I have to be familiar with the code.
